# permissions for end users to edit crons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cron-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-operator
    app.kubernetes.io/part-of: k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: cron-editor-role
rules:
  - apiGroups:
      - webappcron.csye7125-fall2023-group05.cloud
    resources:
      - crons
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - webappcron.csye7125-fall2023-group05.cloud
    resources:
      - crons/status
    verbs:
      - get
