apiVersion: webappcron.csye7125-fall2023-group05.cloud/v1
kind: Cron
metadata:
  labels:
    app.kubernetes.io/name: cron
    app.kubernetes.io/instance: cron-sample
    app.kubernetes.io/part-of: k8s-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: k8s-operator
  name: cron-sample
spec:
  url: "www.google.com"
  retries: 5
  res_code: 200
